"""DOCX export for generated documentation.

Why a separate exporter instead of converting the Markdown: the specification asks
for a clean, editable deliverable. A Markdown-to-DOCX conversion inherits the
renderer's emphasis markers and table pipes; building the document from the same
``payload`` the Markdown renderer reads gives real Word headings, real tables and
real bullet lists, with no markup leaking into the file.

The export is deterministic and read-only: it never re-runs generation and never
touches the database, so a download cannot change what is stored.
"""

from __future__ import annotations

import io
from datetime import datetime, timezone

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt, RGBColor

from app.services.milestone3.common import (
    DOC_ACTION_ITEMS,
    DOC_RISK_REGISTER,
    DOC_USER_STORIES,
    NOT_SPECIFIED,
)
from app.services.milestone3.documentation.renderer import VERDICT_LABELS

#: Placeholder cells are greyed out rather than dropped, so a reader can see at a
#: glance that the field exists and simply is not in the project data.
_PLACEHOLDER_RGB = RGBColor(0x70, 0x70, 0x70)
_CONFLICT_RGB = RGBColor(0xA6, 0x3D, 0x00)


def _is_placeholder(value: str | None) -> bool:
    v = (value or "").strip()
    return not v or v == NOT_SPECIFIED


def _clean(value: str | None) -> str:
    v = (value or "").strip()
    return v if v else NOT_SPECIFIED


def _run(paragraph, text: str, *, italic: bool = False, mono: bool = False):
    """Add a run, styling explicit placeholders and conflict notes distinctly."""
    run = paragraph.add_run(text)
    if _is_placeholder(text):
        run.italic = True
        run.font.color.rgb = _PLACEHOLDER_RGB
    elif text.startswith("Conflict:") or "conflict" in text.lower() and "preserved" in text.lower():
        run.font.color.rgb = _CONFLICT_RGB
    if mono:
        run.font.name = "Consolas"
        run.font.size = Pt(9)
    return run


def _heading(doc, text: str, level: int = 1) -> None:
    doc.add_heading(text, level=level)


def _kv(doc, label: str, value: str | None, *, mono: bool = False) -> None:
    paragraph = doc.add_paragraph()
    paragraph.paragraph_format.space_after = Pt(2)
    run = paragraph.add_run(f"{label}: ")
    run.bold = True
    _run(paragraph, _clean(value), mono=mono)


def _relationship(doc, label: str, items: list | None) -> None:
    rendered = _labels(items)
    _kv(doc, label, "; ".join(rendered) if rendered else NOT_SPECIFIED)


def _labels(items: list | None) -> list[str]:
    out: list[str] = []
    for item in items or []:
        if isinstance(item, dict):
            title = (item.get("title") or "").strip()
            identifier = (item.get("id") or "").strip()
            out.append(f"{identifier} — {title}" if title else identifier)
        else:
            out.append(str(item))
    return out


#: Table style used for every table. Falls back to plain borders when the running
#: python-docx default template does not carry the named accent style.
_TABLE_STYLE = "Light Grid Accent 1"


def _table(doc, headers: list[str], rows: list[list[str]]) -> None:
    table = doc.add_table(rows=1, cols=len(headers))
    try:
        table.style = _TABLE_STYLE
    except KeyError:
        table.style = "Table Grid"
    for cell, text in zip(table.rows[0].cells, headers):
        cell.text = ""
        run = cell.paragraphs[0].add_run(text)
        run.bold = True
    for row in rows:
        cells = table.add_row().cells
        for cell, text in zip(cells, row):
            cell.text = ""
            _run(cell.paragraphs[0], _clean(text))


def _header_block(doc, title: str, project_name: str, basis: str, data: dict | None = None) -> None:
    _heading(doc, title, level=0)
    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.LEFT
    run = subtitle.add_run(project_name or "Project")
    run.bold = True
    run.font.size = Pt(13)

    due = (data or {}).get("project_due_date") or {}
    due_line = _clean(due.get("effective_date"))
    if due.get("source") and due.get("source") != "Not specified":
        due_line = f"{due_line} (source: {due['source']})"
    if due.get("conflict"):
        due_line += (
            " — the uploaded document states a different date, which takes precedence "
            "over the date entered on the project record"
        )
    doc.add_paragraph(f"Project Due Date: {due_line}")
    doc.add_paragraph(
        f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}"
    )
    doc.add_paragraph(f"Basis: {basis}")
    doc.add_paragraph(
        "Generated by the Documentation Generation Agent from the project's "
        "own uploaded documents and existing analysis output. It does not "
        "replace, and never overwrites, the original uploaded files."
    )


def _validation_block(doc, data: dict) -> None:
    validation = data.get("validation") or {}
    if not validation:
        return
    _heading(doc, "Validation and corrections", level=1)
    doc.add_paragraph(
        f"Status: {validation.get('status', NOT_SPECIFIED)} — "
        f"{validation.get('fields_checked', 0)} fields checked, "
        f"{validation.get('supported', 0)} supported by project data, "
        f"{validation.get('corrected', 0)} corrected, "
        f"{validation.get('unsupported_removed', 0)} removed as unsupported, "
        f"{validation.get('not_specified', 0)} not specified in project data, "
        f"{validation.get('conflicts', 0)} conflicts recorded."
    )
    findings = [
        f for f in (validation.get("findings") or [])
        if f.get("verdict") not in (None, "SUPPORTED")
    ]
    if findings:
        _table(
            doc,
            ["Field", "Verdict", "Value kept", "Explanation"],
            [
                [
                    f.get("field") or NOT_SPECIFIED,
                    VERDICT_LABELS.get(f.get("verdict"), f.get("verdict") or NOT_SPECIFIED),
                    f.get("value") or NOT_SPECIFIED,
                    f.get("note") or "",
                ]
                for f in findings
            ],
        )
        doc.add_paragraph()


def _notes_block(doc, notes: list[str] | None) -> None:
    if not notes:
        return
    _heading(doc, "Generation notes", level=1)
    for note in notes:
        doc.add_paragraph(note, style="List Bullet")


# --------------------------------------------------------------------------- #
# Per-type builders
# --------------------------------------------------------------------------- #


def _user_stories(doc, data: dict) -> None:
    stories = data.get("stories") or []
    doc.add_paragraph(f"{len(stories)} grounded user stories.")
    for story in stories:
        _heading(doc, f"{story['id']} · {story['title']}", level=1)
        doc.add_paragraph(
            f"As a {story.get('as_a') or story.get('role')}, "
            f"I want {_clean(story.get('i_want') or story.get('goal'))}, "
            f"so that {_clean(story.get('so_that') or story.get('benefit'))}."
        )
        _kv(doc, "Priority", story.get("priority"))
        _kv(doc, "Status", story.get("status"))
        _kv(doc, "Related requirement", story.get("related_requirement"))
        _kv(doc, "Source document", story.get("source_document"))
        if not _is_placeholder(story.get("source_evidence")):
            _kv(doc, "Source evidence", story.get("source_evidence"), mono=True)
        criteria = story.get("acceptance_criteria") or []
        if criteria:
            _heading(doc, "Acceptance criteria", level=2)
            for criterion in criteria:
                doc.add_paragraph(criterion, style="List Bullet")
        else:
            doc.add_paragraph(
                f"Acceptance criteria: {NOT_SPECIFIED} — no stated criterion could be traced "
                "to the project documents."
            )


def _risk_register(doc, data: dict) -> None:
    entries = data.get("entries") or []
    doc.add_paragraph(
        f"{len(entries)} risks · total exposure {data.get('total_exposure', 0)} · "
        f"highest score {data.get('max_score', 0)}/25"
    )
    if entries:
        _table(
            doc,
            ["Risk ID", "Title", "Category", "Probability", "Impact", "Score", "Severity", "Status"],
            [
                [
                    e["risk_id"],
                    e["title"],
                    e.get("category"),
                    e.get("probability"),
                    e.get("impact"),
                    f"{e['risk_score']}/25",
                    e.get("severity_band"),
                    e.get("status"),
                ]
                for e in entries
            ],
        )
        doc.add_paragraph()
    else:
        doc.add_paragraph(
            f"{NOT_SPECIFIED} No risk records exist for this project, so the register is empty."
        )

    for entry in entries:
        _heading(doc, f"{entry['risk_id']} · {entry['title']}", level=1)
        _kv(doc, "Description", entry.get("description"))
        _kv(doc, "Category", entry.get("category"))
        _kv(doc, "Probability", entry.get("probability"))
        _kv(doc, "Impact", entry.get("impact"))
        _kv(doc, "Risk score", f"{entry['risk_score']}/25 ({_clean(entry.get('severity_band'))})")
        _kv(doc, "Severity", entry.get("severity"))
        _kv(doc, "Status", entry.get("status"))
        _kv(doc, "Owner", entry.get("owner"))
        _kv(doc, "Mitigation", entry.get("mitigation"))
        _kv(doc, "Contingency", entry.get("contingency"))
        _relationship(doc, "Related blockers", entry.get("related_blockers"))
        _relationship(doc, "Related actions", entry.get("related_actions"))
        _kv(doc, "Source document", entry.get("source_document"))
        if not _is_placeholder(entry.get("source_evidence")):
            _kv(doc, "Evidence", entry.get("source_evidence"), mono=True)
        for conflict in entry.get("conflicts") or []:
            paragraph = doc.add_paragraph(style="List Bullet")
            _run(paragraph, f"Conflict: {conflict}")

    excluded = data.get("excluded") or []
    if excluded:
        _heading(doc, "Records kept in their own category", level=1)
        doc.add_paragraph(
            "These rows live in the recorded risk table but are described by the source "
            "documents as blockers or action items. They are listed for traceability and are "
            "not counted as risks."
        )
        _table(
            doc,
            ["Record", "Description", "Classified as", "Reason", "Kept in"],
            [
                [
                    item.get("risk_id"),
                    item.get("title"),
                    item.get("classified_as"),
                    item.get("reason"),
                    item.get("kept_in"),
                ]
                for item in excluded
            ],
        )


def _action_items(doc, data: dict) -> None:
    entries = data.get("entries") or []
    doc.add_paragraph(
        f"{data.get('open', 0)} open of {data.get('total', 0)} · "
        f"{data.get('ai_generated', 0)} AI-generated · "
        f"{data.get('unassigned_count', 0)} without an owner · "
        f"{data.get('missing_due_date_count', 0)} open without a due date"
    )
    if entries:
        _table(
            doc,
            ["Action ID", "Action", "Owner", "Priority", "Due", "Status", "Origin", "Source"],
            [
                [
                    e["action_id"],
                    e["action"],
                    e.get("owner"),
                    e.get("priority"),
                    e.get("due_date"),
                    e.get("status"),
                    e.get("origin"),
                    e.get("source_document"),
                ]
                for e in entries
            ],
        )
        doc.add_paragraph()
    else:
        doc.add_paragraph(
            f"{NOT_SPECIFIED} No tasks or blockers are recorded for this project, so the list "
            "is empty."
        )

    for entry in entries:
        _heading(doc, f"{entry['action_id']} · {entry['action']}", level=1)
        _kv(doc, "Description", entry.get("description"))
        _kv(doc, "Owner", entry.get("owner"))
        _kv(doc, "Priority", entry.get("priority"))
        _kv(doc, "Due date", entry.get("due_date"))
        _kv(doc, "Status", entry.get("status"))
        _kv(doc, "Related risk", entry.get("related_risk"))
        _kv(doc, "Related blocker", entry.get("related_blocker"))
        _kv(doc, "Origin", entry.get("origin"))
        _kv(doc, "Source document", entry.get("source_document"))
        if not _is_placeholder(entry.get("source_evidence")):
            _kv(doc, "Source evidence", entry.get("source_evidence"), mono=True)

        trace = entry.get("due_date_trace") or {}
        if trace:
            _heading(doc, "Due date traceability", level=2)
            _kv(doc, "Administrator-entered date", trace.get("admin_date"))
            _kv(doc, "Date in the source document", trace.get("document_date"))
            _kv(doc, "Effective date", trace.get("effective_date"))
            _kv(doc, "Precedence applied", trace.get("source"))
            _kv(
                doc,
                "Conflict with the administrator-entered date",
                "Yes" if trace.get("conflict") else "No",
            )


_BUILDERS = {
    DOC_USER_STORIES: (_user_stories, "existing uploaded project documents (RAG) + "
                                        "Scope Analysis output"),
    DOC_RISK_REGISTER: (_risk_register, "existing Risk Detection output "
                                        "+ project documents"),
    DOC_ACTION_ITEMS: (_action_items, "existing tasks, AI-detected action items and open blockers"),
}


DOC_TITLES = {
    "user_stories": "PROJECT USER STORIES",
    "risk_register": "PROJECT RISK REGISTER",
    "action_items": "PROJECT ACTION ITEMS",
}


def build_docx(doc_type: str, data: dict, project_name: str) -> bytes:
    """Return the DOCX bytes for one stored payload.

    >>> build_docx("risk_register", {"entries": []}, "Demo")[:2]  # doctest: +ELLIPSIS
    b'PK'
    """
    entry = _BUILDERS.get(doc_type)
    if entry is None:
        raise ValueError(f"Unknown documentation type: {doc_type}")
    builder, basis = entry

    doc = Document()
    style = doc.styles["Normal"]
    style.font.size = Pt(10.5)

    _header_block(
        doc,
        DOC_TITLES.get(doc_type) or data.get("title") or doc_type.replace("_", " ").title(),
        project_name,
        basis,
        data,
    )

    if data.get("insufficient_evidence"):
        doc.add_paragraph(str(data.get("reason") or NOT_SPECIFIED))
    else:
        builder(doc, data)

    _validation_block(doc, data)
    _notes_block(doc, data.get("notes"))
    doc.add_paragraph(
        f"Exported {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} from the stored "
        "generated document."
    )

    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()


__all__ = ["build_docx"]
