"""Markdown rendering for generated documentation.

Rendering is separated from generation so the stored ``payload`` (structured
JSON, used by the UI) and the stored ``content`` (Markdown, used by the
download) can never drift apart — both come from the same dict in one pass.
"""

from __future__ import annotations

from datetime import datetime, timezone

from app.services.milestone3.common import (
    INSUFFICIENT_EVIDENCE,
    NOT_SPECIFIED,
    doc_file_name,
)
from app.services.milestone3.documentation.schemas import UserStory  # noqa: F401  (re-export guard)

#: Human wording for each validator verdict, used in the rendered summary.
VERDICT_LABELS = {
    "SUPPORTED": "Supported",
    "MISSING": "Not specified in project data",
    "CONFLICT": "Conflict recorded",
    "UNSUPPORTED": "Removed as unsupported",
}

# --- helpers ----------------------------------------------------------------


def _clean(value: str | None, fallback: str = NOT_SPECIFIED) -> str:
    v = (value or "").strip()
    return v if v else fallback


def _labels(items: list | None) -> list[str]:
    """Render relationship values, which may be plain ids or ``{id, title}`` maps."""
    out: list[str] = []
    for item in items or []:
        if isinstance(item, dict):
            title = (item.get("title") or "").strip()
            identifier = (item.get("id") or "").strip()
            out.append(f"{identifier} — {title}" if title else identifier)
        else:
            out.append(str(item))
    return out


def _quoted(text: str | None, limit: int = 300) -> str:
    t = (text or "").strip()
    if not t or t == NOT_SPECIFIED:
        return ""
    return t if len(t) <= limit else t[:limit] + "…"


def _due_date_line(data: dict) -> str:
    """``Project Due Date`` rendered from the resolved document-first decision."""
    due = data.get("project_due_date") or {}
    effective = _clean(due.get("effective_date"))
    source = due.get("source") or ""
    trace = f" (source: {source})" if source and source != "Not specified" else ""
    conflict = (
        " — differs from the date entered on the project record, which the document overrides"
        if due.get("conflict")
        else ""
    )
    return f"**Project Due Date:** {effective}{trace}{conflict}"


def _header(project_name: str, title: str, subtitle: str, data: dict | None = None) -> list[str]:
    return [
        f"# {title}",
        "",
        f"**Project:** {project_name}  ",
        _due_date_line(data or {}),
        f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}  ",
        f"**Generated by:** Documentation Generation Agent  ",
        f"**Basis:** {subtitle}",
        "",
        "> This document is AI-generated from the project's own uploaded documents and "
        "existing analysis output. It does not replace, and never overwrites, "
        "the original uploaded files.",
        "",
        "---",
        "",
    ]


def _validation_block(data: dict) -> list[str]:
    """The validation + correction summary the specification requires."""
    validation = data.get("validation") or {}
    if not validation:
        return []
    lines = [
        "## Validation and corrections",
        "",
        f"- **Status:** {validation.get('status', NOT_SPECIFIED)}",
        f"- **Fields checked:** {validation.get('fields_checked', 0)}",
        f"- **Supported by project data:** {validation.get('supported', 0)}",
        f"- **Corrected:** {validation.get('corrected', 0)}",
        f"- **Removed as unsupported:** {validation.get('unsupported_removed', 0)}",
        f"- **Not specified in project data:** {validation.get('not_specified', 0)}",
        f"- **Conflicts recorded:** {validation.get('conflicts', 0)}",
        "",
    ]
    findings = [
        f for f in (validation.get("findings") or [])
        if f.get("verdict") not in (None, "SUPPORTED")
    ]
    if findings:
        lines += [
            "Fields that were not simply supported:",
            "",
            "| Field | Verdict | Value kept | Explanation |",
            "| --- | --- | --- | --- |",
        ]
        for finding in findings:
            lines.append(
                f"| {finding.get('field')} "
                f"| {VERDICT_LABELS.get(finding.get('verdict'), finding.get('verdict'))} "
                f"| {_quoted(finding.get('value'), 80)} "
                f"| {_quoted(finding.get('note'), 160)} |"
            )
        lines.append("")
    return lines


def _footer(notes: list[str]) -> list[str]:
    out = ["", "---", "", "### Generation notes", ""]
    out.extend(f"- {n}" for n in notes)
    out.append("")
    return out


# --- user stories -----------------------------------------------------------


def render_user_stories(data: dict) -> str:
    lines = _header(
        _clean(data.get("project"), "Project"),
        "PROJECT USER STORIES",
        "existing uploaded project documents (RAG) + Scope Analysis output",
        data,
    )

    if data.get("insufficient_evidence"):
        lines += [
            f"**{INSUFFICIENT_EVIDENCE}**",
            "",
            data.get("reason", INSUFFICIENT_EVIDENCE),
            "",
        ]
        if data.get("provider_error"):
            lines += [
                "_Note: the AI provider was unavailable during this run, so no stories "
                "could be produced. This is a provider problem, not a statement about the "
                "project data._",
                "",
            ]
        return "\n".join(lines)

    stories = data.get("stories") or []
    lines.append(f"**{len(stories)} grounded user stories.**")
    lines.append("")

    for story in stories:
        lines += [
            f"### {story['id']} · {story['title']}",
            "",
            f"**As a** {story['role']},  ",
            f"**I want** {story['goal']},  ",
            f"**so that** {_clean(story.get('benefit'))}.",
            "",
            f"- **Priority:** {story.get('priority', 'Medium')}",
            f"- **Status:** {_clean(story.get('status'))}",
            f"- **Related requirement:** {_clean(story.get('related_requirement'))}",
            f"- **Source document:** {_clean(story.get('source_document'))}",
        ]
        quoted = _quoted(story.get("source_evidence"))
        if quoted:
            lines.append(f'- **Source evidence:** "{quoted}"')
        lines.append("")

        criteria = story.get("acceptance_criteria") or []
        if criteria:
            lines += ["**Acceptance criteria**", ""]
            lines.extend(f"- {c}" for c in criteria)
        else:
            lines += [
                f"**Acceptance criteria:** {NOT_SPECIFIED} — no stated criterion could be "
                "traced to the project documents.",
            ]
        lines.append("")

    lines += _validation_block(data)
    lines += _footer([
        "Stories are generated only from requirements explicitly present in the "
        "project's uploaded documents. Stories that could not be traced to a "
        "retrieved document fragment are discarded rather than published.",
        f"Where a benefit or acceptance criteria is not stated in the documents, the field "
        f"reads '{NOT_SPECIFIED}'.",
        "User stories are proposed artifacts for review by the project team; they are not "
        "a contractual scope baseline.",
    ])
    return "\n".join(lines)


# --- risk register ----------------------------------------------------------


def render_risk_register(data: dict) -> str:
    entries = data.get("entries") or []
    lines = _header(
        _clean(data.get("project"), "Project"),
        "PROJECT RISK REGISTER",
        "existing Risk Detection output + project documents",
        data,
    )

    lines += [
        f"**{len(entries)} risks** · total exposure {data.get('total_exposure', 0)} · "
        f"highest score {data.get('max_score', 0)}/25",
        "",
    ]
    if not entries:
        lines += [
            f"**{NOT_SPECIFIED}**",
            "",
            "No risk records exist for this project, so the register is empty. "
            "The register is rebuilt automatically whenever a document is uploaded.",
            "",
        ]
    lines += [
        "| Risk ID | Title | Category | Probability | Impact | Score | Severity | Status |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for e in entries:
        lines.append(
            f"| {e['risk_id']} | {e['title']} | {_clean(e.get('category'))} | "
            f"{_clean(e.get('probability'))} | {_clean(e.get('impact'))} | "
            f"{e['risk_score']}/25 | {_clean(e.get('severity_band'))} | "
            f"{_clean(e.get('status'))} |"
        )
    lines.append("")

    for e in entries:
        lines += [
            f"### {e['risk_id']} · {e['title']}",
            "",
            f"- **Description:** {_clean(e.get('description'))}",
            f"- **Category:** {_clean(e.get('category'))}",
            f"- **Probability:** {_clean(e.get('probability'))}",
            f"- **Impact:** {_clean(e.get('impact'))}",
            f"- **Risk score:** {e['risk_score']}/25 ({_clean(e.get('severity_band'))})",
            f"- **Severity:** {_clean(e.get('severity'))}",
            f"- **Status:** {_clean(e.get('status'))}",
            f"- **Owner:** {_clean(e.get('owner'))}",
            f"- **Mitigation:** {_clean(e.get('mitigation'))}",
            f"- **Contingency:** {_clean(e.get('contingency'))}",
            f"- **Source document:** {_clean(e.get('source_document'))}",
            f"- **Evidence:** {_clean(e.get('source_evidence'))}",
        ]
        blockers = _labels(e.get("related_blockers"))
        actions = _labels(e.get("related_actions"))
        lines.append(
            f"- **Related blockers:** {'; '.join(blockers) if blockers else NOT_SPECIFIED}"
        )
        lines.append(
            f"- **Related actions:** {'; '.join(actions) if actions else NOT_SPECIFIED}"
        )
        for conflict in e.get("conflicts") or []:
            lines.append(f"- **Conflict:** {conflict}")
        lines.append("")

    excluded = data.get("excluded") or []
    if excluded:
        lines += [
            "## Records kept in their own category",
            "",
            "The following rows live in the recorded risk table but are described by the "
            "source documents as blockers or action items. They are listed here for "
            "traceability and are **not** counted as risks.",
            "",
            "| Record | Description | Classified as | Reason | Kept in |",
            "| --- | --- | --- | --- | --- |",
        ]
        for item in excluded:
            lines.append(
                f"| {item.get('risk_id')} | {_clean(item.get('title'))} "
                f"| {_clean(item.get('classified_as'))} | {_clean(item.get('reason'))} "
                f"| {_clean(item.get('kept_in'))} |"
            )
        lines.append("")

    lines += _validation_block(data)
    lines += _footer(data.get("notes") or [])
    return "\n".join(lines)


# --- action items -----------------------------------------------------------


def render_action_items(data: dict) -> str:
    entries = data.get("entries") or []
    lines = _header(
        _clean(data.get("project"), "Project"),
        "PROJECT ACTION ITEMS",
        "existing tasks, AI-detected action items and open blockers",
        data,
    )

    lines += [
        f"**{data.get('open', 0)} open of {data.get('total', 0)}** · "
        f"{data.get('ai_generated', 0)} AI-generated · "
        f"{data.get('unassigned_count', 0)} without an owner · "
        f"{data.get('missing_due_date_count', 0)} open without a due date",
        "",
    ]
    if not entries:
        lines += [
            f"**{NOT_SPECIFIED}**",
            "",
            "No tasks or blockers are recorded for this project, so the list is empty.",
            "",
        ]
    lines += [
        "| Action ID | Action | Owner | Priority | Due | Status | Origin | Source |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for e in entries:
        lines.append(
            f"| {e['action_id']} | {e['action']} | {_clean(e.get('owner'))} | "
            f"{_clean(e.get('priority'))} | {_clean(e.get('due_date'))} | "
            f"{_clean(e.get('status'))} | {_clean(e.get('origin'))} | "
            f"{_clean(e.get('source_document'))} |"
        )
    lines.append("")

    for e in entries:
        lines += [
            f"### {e['action_id']} · {e['action']}",
            "",
            f"- **Description:** {_clean(e.get('description'))}",
            f"- **Owner:** {_clean(e.get('owner'))}",
            f"- **Priority:** {_clean(e.get('priority'))}",
            f"- **Due date:** {_clean(e.get('due_date'))}",
            f"- **Status:** {_clean(e.get('status'))}",
            f"- **Related risk:** {_clean(e.get('related_risk'))}",
            f"- **Related blocker:** {_clean(e.get('related_blocker'))}",
            f"- **Origin:** {_clean(e.get('origin'))}",
            f"- **Source document:** {_clean(e.get('source_document'))}",
            f"- **Source evidence:** {_clean(e.get('source_evidence'))}",
            "",
        ]
        trace = e.get("due_date_trace") or {}
        if trace:
            lines += [
                "**Due date traceability**",
                "",
                f"- **Administrator-entered date:** {_clean(trace.get('admin_date'))}",
                f"- **Date in the source document:** {_clean(trace.get('document_date'))}",
                f"- **Effective date:** {_clean(trace.get('effective_date'))}",
                f"- **Precedence applied:** {_clean(trace.get('source'))}",
                f"- **Conflict with the administrator-entered date:** "
                f"{'Yes' if trace.get('conflict') else 'No'}",
                "",
            ]

    lines += _validation_block(data)
    lines += _footer(data.get("notes") or [])
    return "\n".join(lines)


RENDERERS = {
    "user_stories": render_user_stories,
    "risk_register": render_risk_register,
    "action_items": render_action_items,
}


def render(doc_type: str, data: dict, project_name: str) -> str:
    renderer = RENDERERS.get(doc_type)
    if renderer is None:
        raise ValueError(f"Unknown documentation type: {doc_type}")
    return renderer(data)


__all__ = [
    "VERDICT_LABELS",
    "render",
    "render_user_stories",
    "render_risk_register",
    "render_action_items",
    "doc_file_name",
    "RENDERERS",
]
